# Generated by Django 5.2.1 on 2025-10-01 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_categories_options_alter_users_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='role',
            field=models.CharField(choices=[('Buyer', 'Покупатель'), ('Seller', 'Продавец')], default='Buyer', max_length=20, verbose_name='Роль'),
        ),
    ]
